config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    get 'tickets/create'
  end
  resources :tickets
  root "tickets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/excavator.rb
class Excavator < ApplicationRecord
  belongs_to :ticket
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  has_one :excavator

  def excavator_props
    { 
      name: excavator.company_name, 
      address: excavator.address 
    }
  end
end

app/controllers/api/tickets_controller.rb
require 'json-schema'
module Api
  class TicketsController < ApplicationController
    before_action :parse_json_data, only: [:create]

    def create
      unless valid_json_data?
        render json: { errors: 'Invalid JSON data' }, status: :unprocessable_entity
        return
      end

      service = TicketCreationService.new(@json_data)
      result = service.create_ticket_and_excavator

      if result[:success]
        render json: { message: result[:message] }, status: :created
      else
        render json: { errors: result[:errors] }, status: :unprocessable_entity
      end
    end

    private

    def parse_json_data
      begin
        @json_data = JSON.parse(request.body.read) rescue {}
      rescue Exception => e
        @json_data = {}
      end
    end

    def valid_json_data?
      JSON::Validator.validate(json_schema, @json_data)
    end

    def json_schema
      JSON.parse(File.read('config/schemas/geospatial.json'))
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :find_ticket, only: [:show]

  def index
    @tickets = Ticket.includes(:excavator).all
  end

  def show
    if @ticket
      @geo_json = generate_geo_json(@ticket)
    else
      render_not_found
    end
  end

  private

  def find_ticket
    @ticket = Ticket.find_by_id(params[:id])
  end

  def generate_geo_json(ticket)
    return RGeo::GeoJSON.encode(RGeo::GeoJSON::Feature.new(ticket.well_known_text, nil, ticket.excavator_props))
  end

  def render_not_found
    render json: { error: 'Ticket not found' }, status: :not_found
  end
end

app/helpers/api/tickets_helper.rb
module Api::TicketsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GeospatialApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <link
      rel="stylesheet"
      href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css"
      integrity="sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ=="
      crossorigin=""
    />
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tickets/_ticket.html.erb
<td><%= ticket.request_number %></td>
<td><%= ticket.excavator.address %></td>
<td><%= ticket.request_type %></td>
<td><%= link_to "Show this Map", ticket %></td>

app/views/tickets/index.html.erb
<table>
  <tr>
    <th>Request Number</th>
    <th>Address</th>
    <th>Request Type</th>
    <th>Link</th>
  </tr>
  <% @tickets.each do |ticket| %>
    <tr>
      <%= render ticket %>
    </tr>
  <% end %>
</table>

app/views/tickets/show.html.erb
<h4>
  <%= link_to "Back to main page", tickets_path %>
</h4>
<div data-controller="map" data-map-target="map" data-map-polygon-coordinates="<%= @geo_json.to_json %>" style="height: 800px;"></div>